# Generated by Django 5.1.6 on 2025-02-19 06:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servReq', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='dateTime',
        ),
        migrations.AddField(
            model_name='request',
            name='dateTimeAdded',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 19, 12, 0, 16, 472261)),
        ),
        migrations.AddField(
            model_name='request',
            name='dateTimeResolved',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 19, 12, 0, 16, 472261)),
        ),
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(default='Pending', max_length=15),
        ),
    ]
