# Generated by Django 5.1.6 on 2025-02-19 11:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servReq', '0002_remove_request_datetime_request_datetimeadded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='file',
            field=models.FileField(blank=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='request',
            name='dateTimeAdded',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 19, 16, 44, 1, 182964)),
        ),
        migrations.AlterField(
            model_name='request',
            name='dateTimeResolved',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 19, 16, 44, 1, 182964)),
        ),
    ]
