# Generated by Django 5.1.6 on 2025-02-19 11:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servReq', '0003_request_file_alter_request_datetimeadded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='dateTimeAdded',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 19, 17, 29, 34, 525457)),
        ),
        migrations.AlterField(
            model_name='request',
            name='dateTimeResolved',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 19, 17, 29, 34, 525457)),
        ),
        migrations.AlterField(
            model_name='request',
            name='file',
            field=models.FileField(upload_to='media/'),
        ),
    ]
